#**Inheritance**

**Programs**

**1)Aim:**\
To Develop a python application using Inheritance concept to automate the salary calculation of employee in an organization as per the salary band.

In [ ]:
from prettytable import PrettyTable, ALL 

class Employee: 
  def __init__(self, basic_salary=30000):
    self.basic_salary = basic_salary
    self.epf=0

  def depay(self):
    dacal = int((0.45 * self.basic_salary))
    return dacal 

  def hra(self):
    hracal = int(0.00 * self.basic_salary)
    return hracal

class Manager(Employee):
  def __init__(self, basic_salary):
    super().__init__(basic_salary)
    self.epf = 3000

  def dapay(self):
    dacal = int((0.95 * self.basic_salary))
    return dacal

  def hra(self): 
    hracal = int(0.20 * self.basic_salary)
    return hracal 

  def gross(self):
    mygross = self.basic_salary + self.dapay() + self.hra()
    return mygross

  def net(self):
    return self.gross() - self.epf

  def tax(self): 
    return 0.25 * self.net()



class Engineer(Employee):
  def __init__(self, basic_salary):
    super().__init__(basic_salary)
    self.epf = 2000

  def dapay(self):
    dacal = int((0.80 * self.basic_salary))
    return dacal 

  def hra(self):
    hracal = int(0.15 * self.basic_salary)
    return hracal 

  def gross(self):
    mygross = self.basic_salary + self.dapay() + self.hra()
    return mygross

  def net(self):
    return self.gross() - self.epf

  def tax(self):
    return 0.25 * self.net()

def services_for_manager_class(name):
  man_class = Manager(int(input("Enter your Basic Salary:   ")))
  service = int(input("What do you want to know? \n1.Gross Salary\n2.Net Salary\n3.Tax\n4.Print Pay Roll\n"))
  if service == 1: 
    print(f"Your Gross Salary is {man_class.gross()}")
  elif service == 2: 
    print(f"Your Net Salary is {man_class.net()}")
  elif service == 3: 
    print(f"Your Taxes to be paid on the net salary is {man_class.gross()}")
  elif service == 4: 
    my_table = PrettyTable(["Salary Band", "Value"])
    my_table.hrules = ALL 
    my_table.add_row(["Name", name])
    my_table.add_row(["Basic Salary", man_class.basic_salary])
    my_table.add_row(["DA", man_class.dapay()])
    my_table.add_row(["HRA", man_class.hra()])
    my_table.add_row(["EPF", man_class.epf])
    my_table.add_row(["TAX", man_class.tax()])
    my_table.add_row(["GROSS SALARY", man_class.gross()])
    my_table.add_row(["NET SALARY", man_class.net()])
    print(my_table)
  else: 
    print("Invalid Input!")

def services_for_engineer(name):
  engi_class = Engineer(int(input("Enter your Basic Salary: ")))
  service = int(input("What do you want to know? \n1.Gross Salary\n2.Net Salary\n3.Tax\n4.Print Pay Roll\n"))
  if service == 1:
    print(f"Your Gross Salary  is {engi_class.gross()}")
  elif service == 2: 
    print(f"Your Net Salary is {engi_class.net()}")
  elif service == 3: 
    print(f"Your Taxes to be paid on the net salary is {engi_class.gross()}")
  elif service == 4: 
    my_table = PrettyTable(["Salary Band", "Value"])
    my_table.hrules = ALL 
    my_table.add_row(["Name", name])
    my_table.add_row(["Basic Salary", engi_class.basic_salary])
    my_table.add_row(["DA", engi_class.dapay()])
    my_table.add_row(["HRA", engi_class.hra()])
    my_table.add_row(["EPF", engi_class.epf])
    my_table.add_row(["TAX", engi_class.tax()])
    my_table.add_row(["GROSS SALARY", engi_class.gross()])
    my_table.add_row(["NET SALARY", engi_class.net()])
    print(my_table)
  else: 
    print("Invalid Input!")

def menu():
  name = input("Enter your name: ")
  engi_or_man = int(input("Enter your Designation:\n1.Manager\n2.Engineer\n"))
  if engi_or_man == 1: 
    services_for_manager_class(name)
  elif engi_or_man == 2: 
    services_for_manager_class(name)
  else: 
    print("Invalid Input!")

if __name__ == '__main__':
  choice = ''
  while 1: 
    menu()
    choice = input("Another Service? Y/N: ")
    if choice == "N" or choice == "n":
      break
    else: 
      continue

Enter your name: Ruban
Enter your Designation:
1.Manager
2.Engineer
1
Enter your Basic Salary:   30000
What do you want to know?
1.Gross Salary
2.Net Salary
3.Tax
4.Print Pay Roll
4
+--------------+---------+
| Salary Band  |  Value  |
+--------------+---------+
|     Name     |  Ruban  |
+--------------+---------+
| Basic Salary |  30000  |
+--------------+---------+
|      DA      |  28500  |
+--------------+---------+
|     HRA      |   6000  |
+--------------+---------+
|     EPF      |   3000  |
+--------------+---------+
|     TAX      | 15375.0 |
+--------------+---------+
| GROSS SALARY |  64500  |
+--------------+---------+
|  NET SALARY  |  61500  |
+--------------+---------+
Another Service? Y/N: Y
Enter your name: Gino
Enter your Designation:
1.Manager
2.Engineer
2
Enter your Basic Salary:   20000
What do you want to know?
1.Gross Salary
2.Net Salary
3.Tax
4.Print Pay Roll
4
+--------------+---------+
| Salary Band  |  Value  |
+--------------+---------+
|     Name     |   Gino  |
+--------------+---------+
| Basic Salary |  20000  |
+--------------+---------+
|      DA      |  19000  |
+--------------+---------+
|     HRA      |   4000  |
+--------------+---------+
|     EPF      |   3000  |
+--------------+---------+
|     TAX      | 10000.0 |
+--------------+---------+
| GROSS SALARY |  43000  |
+--------------+---------+
|  NET SALARY  |  40000  |
+--------------+---------+
Another Service? Y/N: N

**Output**
Enter your name: Ruban \
Enter your Designation:\
1.Manager\
2.Engineer\
1\
Enter your Basic Salary:   5000\
What do you want to know? \
1.Gross Salary\
2.Net Salary\
3.Tax\
4.Prin\t Pay Roll
1\
Your Gross Salary is 10750\
Another Service? Y/N: Y\
Enter your name: Ruban \
Enter your Designation:\
1.Manager\
2.Engineer\
2\
Enter your Basic Salary:   4500\
What do you want to know? \
1.Gross Salary\
2.Net Salary\
3.Tax\
4.Print Pay Roll\
4\
![image.png]()\
Another Service? Y/N: N

**2)Aim:**\
To write a python program to calculate the wages using inheritance

In [ ]:

class Worker: 
  def __init__(self, name, salaryrate):
    self.name = name 
    self.salaryrate = salaryrate

  def ComPay(self, hours):
    return hours * self.salaryrate

class DailyWorker(Worker):
  def __init__(self, name, salaryrate, days):
    self.days = days
    super().__init__(name, salaryrate)

class WorkerWithSalary(Worker):
  def __init__(self, name, salaryrate):
    super().__init__(name, salaryrate)
  def ComPay(self, salaryrate):
    return 40*self.salaryrate

if __name__ == '__main__':
  print("<-------------------------Daily Wage Worker------------------------->")
  x = DailyWorker(input("Enter name: "), int(input("Enter Salary Rate: ")), int(input("Enter the no of days worked: ")))
  print(f"Mr.{x.name} earns Rs.{x.ComPay(x.days)} for {x.days} day(s)\n")
  print("<-------------------------Worker with salary------------------------->")
  y = WorkerWithSalary(input("Enter Name: "), int(input("Enter Salary Rate: ")))
  print(f"Mr.{y.name} earns Rs.{y.ComPay(x.days)} for 40 hours")

<-------------------------Daily Wage Worker------------------------->
Enter name: Ruban
Enter Salary Rate: 1000
Enter the no of days worked: 4
Mr.Ruban  earns Rs.4000 for 4 day(s)

<-------------------------Worker with salary------------------------->
Enter Name: Gino
Enter Salary Rate: 4000
Mr.Gino  earns Rs.160000 for 40 hours

**Output:**\
<-------------------------Daily Wage Worker------------------------->\
Enter name: Ruban \
Enter Salary Rate: 500\
Enter the no of days worked: 3\
Mr.Ruban  earns Rs.1500 for 3 day(s)\
\
<-------------------------Worker with salary------------------------->\
Enter Name: Gino \
Enter Salary Rate: 5000\
Mr.Gino  earns Rs.200000 for 40 hours

**3)Aim:**\
To write a python program to design a ATM Machine using Inheritance.

In [ ]:

class CashTree:
    def __init__(self, name, pin, codeno=1234, location='Chennai', balance=60000):
        self.pin = pin
        self.name = name
        self.codeno = codeno
        self.location = location
        self.balance = balance

    def ViewBal(self):
        return self.balance

    def Withdraw(self, wdamount):
        self.wdamount = wdamount
        if wdamount > 20000:
          print("Daily Withdrawal limits of Rs.20000 only.")
        elif wdamount > self.balance:
            print("Insufficient Funds")       
        else:
            return f"Remaining Balance: {self.balance - wdamount}"

    def Deposit(self, damount):
        self.damount = damount
        if damount > 0:
            return f"Your Balance: {self.balance + int(damount)}"
        else:
            print("Invalid input.")


class SBI_Bank(CashTree):
    def __init__(self, name, accno, location, balance):
        super().__init__(name, location, balance)
        self.accno = accno

    def details(self):
        print("---------------STATE BANK OF INDIA---------------")
        print(f"Name:           {self.name}")
        print(f"Acc No.:        {self.accno}")
        print(f"Location:       {self.location}")
        print(f"Balance:        {self.balance}")

    def chequedep(self):
        chequeno = input("Enter 6 digit Cheque number: ")
        if len(chequeno) == 6:
            print("Cheque has been deposited.")

    def make_fd(self):
        fdamt = int(input("Enter Principle Amount: "))
        time = int(input("Enter the number of years: "))
        print("ROI: 6.5% PA")
        confim = int(input("Press 1 to confirm. Press 2 to decline:  "))
        simple_interest = fdamt + ((fdamt * time * 6.5) / 100)
        if confim == 1:
            print(f"Thank you!. please collect Rs.{simple_interest} after {time} years")
        else:
            print("Transaction Cancelled.")


class HDFC_Bank(SBI_Bank):
    def __init__(self, name, accno, location="Tirunelveli", balance=25000):
        super().__init__(name, accno, location, balance)
        self.accno = accno
        self.balance = balance

    def details(self):
        print("---------------HDFC BANK---------------")
        print(f"Name:           {self.name}")
        print(f"Acc No.:        {self.accno}")
        print(f"Location:       {self.location}")
        print(f"Balance:        {self.balance}")

    def make_fd(self):
        fdamt = int(input("Enter Principle Amount: "))
        time = int(input("Enter the number of years: "))
        print("ROI: 5.5% PA")
        confim = int(input("Press 1 to confirm. Press 2 to decline:  "))
        simple_interest = fdamt + ((fdamt * time * 5.5) / 100)
        if confim == 1:
            print(f"Thank you!. please collect Rs.{simple_interest} after {time} years")
        else:
            print("Transaction Cancelled.")
    def Withdraw(self, wdamount):
        self.wdamount = wdamount
        if wdamount > 50000:
          print("Daily Withdrawal limits of Rs.50000 only.")
        elif wdamount > self.balance:
            print("Insufficient Funds")       
        else:
            return f"Remaining Balance: {self.balance - wdamount}"


def menu():
    n = int(input("What would you like to do today.\n1.Banking Service\n2.ATM Services\n"))
    if n == 1:
        select = int(input("Select Bank \n1.State Bank of India\n2.HDFC Bank\n"))
        if select == 1:
            sbibank = SBI_Bank("Ruban", int(input("Enter your account no: ")), "Chennai", 50000)
            sub_menu = int(input("What would you like to do?\n1.View Balance\n2.Withdrawal"
                                 "\n3.Deposit\n4.Cheque Deposit\n5.Make FD\n6.View Details\n"))
            if sub_menu == 1:
                print(f"Available Balance: Rs.{sbibank.ViewBal()}")
            elif sub_menu == 2:
                print(sbibank.Withdraw(int(input("Enter the amount you want to withdraw: Rs. "))))
            elif sub_menu == 3:
                print(sbibank.Deposit(int(input("Enter the amount you want to Deposit: Rs. "))))
            elif sub_menu == 4:
                sbibank.chequedep()
            elif sub_menu == 5:
                sbibank.make_fd()
            elif sub_menu == 6:
                sbibank.details()
            else:
                print("Invalid Input")
        elif select == 2:
            hdfcbank = HDFC_Bank("Gino", int(input("Enter your account no: ")), "Tirunelveli", 20000)
            sub_menu = int(input(
                "What would you like to do?\n1.View Balance\n2.Withdrawal\n3.Deposit\n4.Cheque Deposit\n5.Make FD\n6.View Details\n"))
            if sub_menu == 1:
                print(f"Available Balance: Rs.{hdfcbank.ViewBal()}")
            elif sub_menu == 2:
                print(hdfcbank.Withdraw(int(input("Enter the amount you want to withdraw: Rs. "))))
            elif sub_menu == 3:
                print(hdfcbank.Deposit(int(input("Enter the amount you want to Deposit: Rs. "))))
            elif sub_menu == 4:
                hdfcbank.chequedep()
            elif sub_menu == 5:
                hdfcbank.make_fd()
            elif sub_menu == 6:
                hdfcbank.details()
            else:
              print("Invalid Input")

    elif n == 2:
        bin = int(input("Enter 4 digit ATM pin:    "))
        atm = CashTree(name = input("Enter your Name:          "), pin=bin)
        if len(str(bin)) == 4 and str(bin).isdigit():
            sub_menu = int(input(
                "What would you like to do?\n1.View Balance\n2.Withdrawal\n3.Deposit\n"))
            if sub_menu == 1:
                print(f"Available Balance: Rs.{atm.ViewBal()}\n")
            elif sub_menu == 2:
                print(atm.Withdraw(int(input("Enter the amount you want to withdraw: Rs. "))))
            elif sub_menu == 3:
                print(atm.Deposit(int(input("Enter the amount you want to Deposit: Rs. "))))
            else:
                print("Invalid Input")
    else:
        print("Invalid Input")


if __name__ == '__main__':
    print("Welcome!")
    choice = ''
    while 1:
        menu()
        choice = input("Another Service ? Y /N :  ")
        if choice == "N" or choice == "n":
          break
        else:
          continue

Welcome!
What would you like to do today.
1.Banking Service
2.ATM Services
1
Select Bank
1.State Bank of India
2.HDFC Bank
1
Enter your account no: 123123123
What would you like to do?
1.View Balance
2.Withdrawal
3.Deposit
4.Cheque Deposit
5.Make FD
6.View Details
6
---------------STATE BANK OF INDIA---------------
Name:           Ruban
Acc No.:        123123123
Location:       Chennai
Balance:        60000
Another Service ? Y /N :  N

**Output:**\
Welcome!\
What would you like to do today.\
1.Banking Service\
2.ATM Services\
1\
Select Bank \
1.State Bank of India\
2.HDFC Bank\
1\
Enter your account no: 123123123\
What would you like to do?\
1.View Balance\
2.Withdrawal\
3.Deposit\
4.Cheque Deposit\
5.Make FD\
6.View Details\
6\
---------------STATE BANK OF INDIA---------------\
Name:           Ruban\
Acc No.:        123123123\
Location:       Chennai\
Balance:        60000\
Another Service ? Y /N :  N\